apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nativeimagebuildconfigs.demos.graalvm.oracle.com
spec:
  additionalPrinterColumns:
    - JSONPath: .metadata.creationTimestamp
      name: age
      type: date
    - JSONPath: .status.buildCounter
      name: counter
      type: integer
    - JSONPath: .status.builderPod
      name: builderPod
      type: string
    - JSONPath: .status.status
      name: status
      type: string
    - JSONPath: .spec.source.gitUri
      name: source
      type: string
  group: demos.graalvm.oracle.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
      # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: nativeimagebuildconfigs
    singular: nativeimagebuildconfig
    kind: NativeImageBuildConfig
    shortNames:
      - ni
      - nib
      - nibc
  validation:
    openAPIV3Schema:
      type: object
      properties:
        status:
          type: object
          properties:
            status:
              type: string
            buildCounter:
              type: integer
            buiderPod:
              type: String
        spec:
          type: object
          properties:
            source:
              type: object
              properties:
                gitUri:
                  type: string
                gitRef:
                  type: string
                mainClass:
                  type: string
                contextDir:
                  type: string
            destination:
              type: object
              properties:
                imageRepository:
                  type: string
                imageTag:
                  type: string
                baseImage:
                  type: string
                pushPullSecret:
                  type: string
                deployment:
                  type: string
            options:
              type: object
              properties:
                debug:
                  type: boolean
                mvnBuildCommand:
                  type: string
                nativeImageOptions:
                  type: array
                  items:
                    type: string
