apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nativeimagebuildconfigs.demos.graalvm.oracle.com
spec:
  group: demos.graalvm.oracle.com
  scope: Namespaced
  names:
      # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    categories:
      - all
    plural: nativeimagebuildconfigs
    singular: nativeimagebuildconfig
    kind: NativeImageBuildConfig
    shortNames:
      - ni
      - nib
      - nibc
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .metadata.creationTimestamp
          name: age
          type: date
        - jsonPath: .status.buildCounter
          name: counter
          type: integer
        - jsonPath: .status.builderPod
          name: builderPod
          type: string
        - jsonPath: .status.status
          name: status
          type: string
        - jsonPath: .spec.source.gitUri
          name: source
          type: string
        - jsonPath: .spec.destination.imageRepository
          name: target
          type: string
        - jsonPath: .spec.destination.imageTag
          name: tag
          type: string
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                status:
                  type: string
                buildCounter:
                  type: integer
                buiderPod:
                  type: String
            spec:
              type: object
              properties:
                source:
                  type: object
                  required:
                    - gitUri
                    - mainClass
                  properties:
                    gitUri:
                      type: string
                    gitRef:
                      type: string
                    mainClass:
                      type: string
                    contextDir:
                      type: string
                destination:
                  type: object
                  required:
                   - imageRepository
                  properties:
                    imageRegistry:
                      type: string
                    imageRepository:
                      type: string
                    imageTag:
                      type: string
                    baseImage:
                      type: string
                    pushPullSecret:
                      type: string
                    deployment:
                      type: string
                options:
                  type: object
                  properties:
                    debug:
                      type: boolean
                    mvnBuildCommand:
                      type: string
                    nativeImageOptions:
                      type: array
                      items:
                        type: string

