apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-10T12:28:25Z"
  labels:
    com.oracle.graalvm.nativeimagebuildconfig: "true"
  name: nibc-cm
data:
  application.properties: |
    app.builder.image=nelvadas/native-image-builder:1.0.1