apiVersion: demos.graalvm.oracle.com/v1alpha1
kind: NativeImageBuildConfig
metadata:
  name: hello-nib
  labels:
    app: graal-demos
spec:
  source:
    gitUri: "https://github.com/nelvadas/graalvm-helloworld-nativeimage.git"
    gitRef: "main"
    contextDir: "."
    mainClass: com.oracle.graalvm.demos.hellonative.App
  destination:
    imageRegistry: docker.io
    imageRepository: nelvadas/graalvm-helloworld-nativeimage
    imageTag: '1.0.0-demo3'
    baseImage: ubuntu:18.04
    deployment: hello
    pushPullSecret: registrycreds
  options:
    debug: true
    mvnBuildCommand: ''
    nativeImageBuildOptions:
      - '-H:+ReportExceptionStackTraces'
      - '-H:+ReportUnsupportedElementsAtRuntime'
      - '-H:+AddAllCharsets'
      - '--no-server '
      - '--no-fallback'
