apiVersion: demos.graalvm.oracle.com/v1alpha1
kind: NativeImageBuildConfig
metadata:
  name: test-nib
  labels:
    app: graal-demos
spec:
  source:
    gitUri: "https://github.com/nelvadas/graalvm-helloworld-nativeimage.git"
    mainClass: com.demo.test
  destination:
#    imageRepository: docker.io/nelvadas/graalvm-helloworld-nativeimage
    imageTag: '1.0.0'
    baseImage: alpine
    deployment: hello
    pushPullSecret: dockerhubTokenSecret
  options:
    debug: true
    mvnBuildCommand: ''
    nativeImageBuildOptions:
      - '-H:+ReportExceptionStackTraces'
      - '-H:+ReportUnsupportedElementsAtRuntime'
      - '-H:+AddAllCharsets'
